apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: subramanian28/appmonitoring:latest
          ports:
            - containerPort:  3000
---

apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    job: node-api
    app: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-service-monitor 
  labels:
    release: prometheus
    app: prometheus
spec: 
  jobLabel: job
  endpoints: 
    - interval: 30s
      port: web
      path: /swagger-stats/metrics
  selector: 
    matchLabels:
      app: api      




    
